### ISSUE TITLE
Fails to submit block batch extrinsic on `test-a` environment

### ISSUE THREAD

**Issue by isSerge** [subspace/subspace-relayer#115]
Relayer on `test-a` environment occasionally has the following error when submitting block batch extrinsic to Subspace node:
```
relayer_1  | [2022-04-01 13:21:22] ERROR: sendBlocksBatchTx retry error:
relayer_1  |     Error: Dropped
relayer_1  |         at /dist/target.js:49:28
relayer_1  |         at Timeout._onTimeout (/node_modules/@polkadot/api/promise/decorateMethod.cjs:69:24)
relayer_1  |         at listOnTimeout (node:internal/timers:559:17)
relayer_1  |         at processTimers (node:internal/timers:502:7)
```

Errors disappear after the restart but appear again over time.

**Comment by isSerge** [comment]
same issue on `test-b` now
